title: 
description:Collection of notes connected with software engineering
author: MB
github: https://github.com/mbero
about: Software engineering notes
google_analytics: UA-154125713-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/mbero546"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/marcin-berendt/"
    - icon: fa-github
      link: "https://github.com/mbero"

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
     # url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://mbero.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
